--- giflib-5.1.7.orig/Makefile	2019-03-10 16:06:28.000000000 -0300
+++ giflib-5.1.7/Makefile	2019-03-14 16:00:18.234622134 -0300
@@ -6,7 +6,8 @@
 # of code space in the shared library.
 
 #
-CC    = gcc
+# don't hardcode CC
+# CC    = gcc
 OFLAGS = -O0 -g
 #OFLAGS  = -O2 -fwhole-program
 CFLAGS  = -std=gnu99 -fPIC -Wall -Wno-format-truncation $(OFLAGS)
@@ -16,7 +17,8 @@
 TAR = tar
 INSTALL = install
 
-PREFIX = /usr/local
+# use conda PREFIX variable
+# PREFIX = /usr/local
 BINDIR = $(PREFIX)/bin
 INCDIR = $(PREFIX)/include
 LIBDIR = $(PREFIX)/lib
@@ -24,7 +26,8 @@
 
 # No user-serviceable parts below this line
 
-VERSION=$(shell getversion)
+# use conda env var for version
+# VERSION=$(shell getversion)
 LIBMAJOR=7
 LIBMINOR=1
 LIBPOINT=0
@@ -61,7 +64,8 @@
 LDLIBS=libgif.a -lm
 
 all: libgif.so libgif.a $(UTILS)
-	$(MAKE) -C doc
+	# don't build the docs b/c it requires xmlto
+	# $(MAKE) -C doc
 
 $(UTILS):: libgif.a
 
