--- giflib-5.2.0.orig/Makefile	2019-06-24 04:43:41.000000000 -0300
+++ giflib-5.2.0/Makefile	2019-06-24 10:36:24.249660419 -0300
@@ -14,7 +14,8 @@
 TAR = tar
 INSTALL = install
 
-PREFIX = /usr/local
+# use conda PREFIX variable
+# PREFIX = /usr/local
 BINDIR = $(PREFIX)/bin
 INCDIR = $(PREFIX)/include
 LIBDIR = $(PREFIX)/lib
@@ -22,7 +23,8 @@
 
 # No user-serviceable parts below this line
 
-VERSION:=$(shell ./getversion)
+# use conda env var for version
+# VERSION=$(shell getversion)
 
 SOURCES = dgif_lib.c egif_lib.c gifalloc.c gif_err.c gif_font.c \
 	gif_hash.c openbsd-reallocarray.c
@@ -58,7 +60,8 @@
 LDLIBS=libgif.a -lm
 
 all: libgif.so libgif.a libutil.so libutil.a $(UTILS)
-	$(MAKE) -C doc
+	# don't build the docs b/c it requires xmlto
+	# $(MAKE) -C doc
 
 $(UTILS):: libgif.a libutil.a
 
