{% set version = "5.1.5" %}

package:
  name: giflib
  version: {{ version }}

source:
  url: http://downloads.sourceforge.net/project/giflib/giflib-{{ version }}.tar.gz
  sha256: b105046665089149fc16e20a59f54e70ee829b61168a46881f5037469ff4058f

build:
  number: 0
  # the sln file from the URL below is gone :-/
  # http://www.chemformatter.com/build-with-visual-studio-2015/giflib/giflib-5.1.4-vs14.zip
  skip: true  # [win]
  run_exports:
    # SONAME changes at minor revs.
    #    https://abi-laboratory.pro/tracker/timeline/giflib/
    - {{ pin_subpackage('giflib', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}

test:
  commands:
    - gif2rgb -h  # [not win]
    - gifbuild -h  # [not win]
    - gifclrmp -h  # [not win]
    - gifecho -h  # [not win]
    - giffix -h  # [not win]
    - gifinto -h  # [not win]
    - giftext -h  # [not win]
    - gif2rgb.exe -h  # [win]
    - gifbuild.exe -h  # [win]
    - gifclrmp.exe -h  # [win]
    - gifecho.exe -h  # [win]
    - giffix.exe -h  # [win]
    - gifinto.exe -h  # [win]
    - giftext.exe -h  # [win]

about:
  home: http://giflib.sourceforge.net
  license: MIT
  license_file: COPYING
  summary: Library for reading and writing gif images

extra:
  recipe-maintainers:
    - ocefpaf
    - 183amir
    - msarahan
